Repository kcurtet/ImmoPHPSummer, pull requests merged in 2019-07, with the labels that each got.

#1 feat: README.md Nueva descripcción e instrucciones para instalar
  README.md
Labels: documentation

#2 Nuevo usuario por defecto
  app/Http/Controllers/HomeController.php
  database/seeds/DatabaseSeeder.php
  database/seeds/UsersTableSeeder.php
  resources/views/auth/login.blade.php
  resources/views/auth/passwords/email.blade.php
  resources/views/auth/passwords/reset.blade.php
  resources/views/auth/register.blade.php
  resources/views/auth/verify.blade.php
  resources/views/home.blade.php
  resources/views/layouts/app.blade.php
  routes/web.php
Labels: enhancement

#3 Created usertype model migration and seeder
  README.md
  app/User.php
  app/UserType.php
  database/migrations/2019_07_25_082601_create_user_types_table.php
  database/migrations/2019_07_25_094152_add_usertype_id_to_users_table.php
  database/seeds/DatabaseSeeder.php
  database/seeds/UserTypeSeeder.php
  database/seeds/UsersTableSeeder.php
Labels: enhancement

#8 Fix database seeder and user fillable
  app/User.php
  database/seeds/DatabaseSeeder.php
Labels: bug, enhancement

#9 Created model migrations seeder for zones
  app/Province.php
  app/Zone.php
  database/migrations/2019_07_25_151412_create_zones_table.php
  database/seeds/DatabaseSeeder.php
  database/seeds/ZoneTableSeeder.php
Labels: enhancement

#10 fix: He cambiado Zone por ZoneTableSeeder
  database/seeds/DatabaseSeeder.php
Labels: bug

#13 feat: add seeder for Climate
  database/seeds/ClimateTableSeeder.php
  database/seeds/DatabaseSeeder.php
Labels: enhancement

#32 some changes on views login and register
  resources/lang/es/messages.php
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
Labels: enhancement

#33 Add houses to home
  app/Http/Controllers/HomeController.php
  resources/views/welcome.blade.php
Labels: enhancement

#34 Add photos to house model
  app/House.php
  app/Photo.php
  database/seeds/DatabaseSeeder.php
Labels: enhancement

#41 welcome view updated
  public/css/app.css
  resources/sass/_home.scss
  resources/views/layouts/app.blade.php
  resources/views/welcome.blade.php
Labels: enhancement

#43 House controller
  app/House.php
  app/Http/Controllers/HouseController.php
  database/migrations/2019_07_26_092530_create_contracts_table.php
  database/migrations/2019_07_26_094340_create_houses_table.php
  database/seeds/ContractTableSeeder.php
  database/seeds/HousesTableSeeder.php
  resources/lang/es/messages.php
  resources/views/admin/houses/create.blade.php
  resources/views/admin/houses/edit.blade.php
  resources/views/admin/houses/index.blade.php
  resources/views/admin/houses/show.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: enhancement

#45 Updated filter view
  package-lock.json
  package.json
  public/css/app.css
  public/css/jquery-ui.css
  public/js/app.js
  public/js/jquery-3.4.1.min.js
  public/js/jquery-ui.js
  resources/js/app.js
  resources/sass/_filter.scss
  resources/sass/_home.scss
  resources/sass/app.scss
  resources/views/includes/filter.blade.php
  resources/views/layouts/app.blade.php
  resources/views/welcome.blade.php
Labels: enhancement

#46 Province controller
  app/Http/Controllers/ProvinceController.php
  app/Province.php
  resources/lang/es/messages.php
  resources/views/admin/provinces/create.blade.php
  resources/views/admin/provinces/edit.blade.php
  resources/views/admin/provinces/index.blade.php
  resources/views/admin/provinces/show.blade.php
  routes/web.php
Labels: enhancement

#48 fix: updated admin menu
  database/migrations/2019_07_25_094152_add_usertype_id_to_users_table.php
  resources/lang/es/messages.php
  resources/views/admin/houses/create.blade.php
  resources/views/admin/index.blade.php
  resources/views/admin/zones/index.blade.php
  resources/views/includes/adminNav.blade.php
  resources/views/layouts/app.blade.php
  resources/views/welcome.blade.php
Labels: enhancement

#49 Mejorarndo un poco el admin
  app/Http/Controllers/AdminController.php
  resources/lang/es/messages.php
  resources/views/admin/index.blade.php
  resources/views/admin/users/index.blade.php
  resources/views/includes/adminNav.blade.php
  routes/web.php
Labels: enhancement

#52 Añadido el disclaimer para cookies
  composer.json
  composer.lock
  resources/lang/vendor/cookieConsent/de/texts.php
  resources/lang/vendor/cookieConsent/el/texts.php
  resources/lang/vendor/cookieConsent/en/texts.php
  resources/lang/vendor/cookieConsent/es/texts.php
  resources/lang/vendor/cookieConsent/et/texts.php
  resources/lang/vendor/cookieConsent/fr/texts.php
  resources/lang/vendor/cookieConsent/hu/texts.php
  resources/lang/vendor/cookieConsent/nb/texts.php
  resources/lang/vendor/cookieConsent/nl/texts.php
  resources/lang/vendor/cookieConsent/pl/texts.php
  resources/lang/vendor/cookieConsent/pt/texts.php
  resources/lang/vendor/cookieConsent/ru/texts.php
  resources/lang/vendor/cookieConsent/sk/texts.php
  resources/lang/vendor/cookieConsent/sv/texts.php
  resources/lang/vendor/cookieConsent/tr/texts.php
  resources/views/vendor/cookieConsent/dialogContents.blade.php
  resources/views/vendor/cookieConsent/index.blade.php
  resources/views/welcome.blade.php
Labels: enhancement

#53 Some fixes
  resources/lang/es/messages.php
  resources/views/admin/index.blade.php
  resources/views/welcome.blade.php
Labels: bug

#54 feat: add filters to welcome HomeController@index
  app/Http/Controllers/HomeController.php
Labels: enhancement

#56 fix: users modal form action
  resources/views/admin/users/index.blade.php
Labels: bug

#63 fix: tlf in welcome
  resources/views/welcome.blade.php
Labels: enhancement

#66 fix: reduce html in welcome and footer
  public/css/app.css
  public/js/app.js
  resources/sass/_filter.scss
  resources/sass/_footer.scss
  resources/sass/_home.scss
  resources/sass/app.scss
  resources/views/includes/footer.blade.php
  resources/views/welcome.blade.php
Labels: enhancement

#72 feat: ajax csrf token
  public/css/app.css
  public/js/app.js
  resources/js/app.js
Labels: bug

#76 fix: added style to filters
  app/Http/Controllers/HouseController.php
  package-lock.json
  package.json
  public/css/app.css
  public/images/ui-bg_glass_55_fbf9ee_1x400.png
  public/images/ui-bg_glass_65_ffffff_1x400.png
  public/images/ui-bg_glass_75_dadada_1x400.png
  public/images/ui-bg_glass_75_e6e6e6_1x400.png
  public/images/ui-bg_glass_95_fef1ec_1x400.png
  public/images/ui-bg_highlight-soft_75_cccccc_1x100.png
  public/images/ui-icons_222222_256x240.png
  public/images/ui-icons_2e83ff_256x240.png
  public/images/ui-icons_454545_256x240.png
  public/images/ui-icons_888888_256x240.png
  public/images/ui-icons_cd0a0a_256x240.png
  public/js/app.js
  public/js/jquery-ui.js
  resources/images/ui-bg_glass_55_fbf9ee_1x400.png
  resources/images/ui-bg_glass_65_ffffff_1x400.png
  resources/images/ui-bg_glass_75_dadada_1x400.png
  resources/images/ui-bg_glass_75_e6e6e6_1x400.png
  resources/images/ui-bg_glass_95_fef1ec_1x400.png
  resources/images/ui-bg_highlight-soft_75_cccccc_1x100.png
  resources/images/ui-icons_222222_256x240.png
  resources/images/ui-icons_2e83ff_256x240.png
  resources/images/ui-icons_454545_256x240.png
  resources/images/ui-icons_888888_256x240.png
  resources/images/ui-icons_cd0a0a_256x240.png
  resources/js/.eslintrc.js
  resources/js/app.js
  resources/js/bootstrap.js
  resources/js/filters.js
  resources/js/jquery-ui.js
  resources/sass/_home.scss
  resources/sass/app.scss
  resources/sass/jquery-ui.scss
  resources/sass/jquery-ui.structure.scss
  resources/sass/jquery-ui.theme.scss
  resources/views/admin/houses/create.blade.php
  resources/views/admin/houses/show.blade.php
  resources/views/includes/filter.blade.php
  resources/views/includes/footer.blade.php
  resources/views/layouts/admin.blade.php
  resources/views/layouts/app.blade.php
  resources/views/show.blade.php
  resources/views/welcome.blade.php
Labels: enhancement

#84 fix: routes changed to namespace Admin and alias admin.
  app/Http/Controllers/Admin/AdminController.php
  app/Http/Controllers/Admin/CommentController.php
  app/Http/Controllers/Admin/HouseController.php
  app/Http/Controllers/Admin/ProvinceController.php
  app/Http/Controllers/Admin/UserController.php
  app/Http/Controllers/Admin/ZoneController.php
  app/Http/Controllers/HomeController.php
  resources/js/jquery-ui.js
  resources/views/admin/comments/index.blade.php
  resources/views/admin/houses/create.blade.php
  resources/views/admin/houses/edit.blade.php
  resources/views/admin/houses/index.blade.php
  resources/views/admin/houses/show.blade.php
  resources/views/admin/index.blade.php
  resources/views/admin/provinces/create.blade.php
  resources/views/admin/provinces/edit.blade.php
  resources/views/admin/provinces/index.blade.php
  resources/views/admin/provinces/show.blade.php
  resources/views/admin/users/create.blade.php
  resources/views/admin/users/edit.blade.php
  resources/views/admin/users/index.blade.php
  resources/views/admin/zones/create.blade.php
  resources/views/admin/zones/edit.blade.php
  resources/views/admin/zones/index.blade.php
  resources/views/includes/adminNav.blade.php
  resources/views/includes/header.blade.php
  routes/web.php
Labels: enhancement
